In [5]:
import numpy as np

### Dot operation

In [98]:
a,b = np.arange(3),np.arange(3,6)

In [100]:
print(a)
print(b)

[0 1 2]
[3 4 5]


In [102]:
np.dot(a,b) #0*1 = 0, 1*4 = 4, 2*5 = 10, 0+4+10 = 14 

14

In [104]:
print(a @ b) #same

14


### Matrix multiplication

In [157]:
c = np.arange(40,44).reshape(2,2)
d = np.arange(20,24).reshape(2,2)
print(c)
print(d)

result = np.matmul(c, d)
print(result)

[[40 41]
 [42 43]]
[[20 21]
 [22 23]]
[[1702 1783]
 [1786 1871]]


### Determinant & inverse

In [179]:
a = np.array([[1,2],
              [5,6]])
np.linalg.det(a)

-3.999999999999999

In [183]:
b = np.array([[4,7],[2,6]])
np.linalg.inv(b)

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

## Eigenvalues & eigenvectors

In [16]:
a = np.array([[1,-7],[3,5]])
eigenvalues,eigenvectors = np.linalg.eig(a)

print("eigenvalues:",eigenvalues)
print("eigenvectors:",eigenvectors)

eigenvalues: [3.+4.12310563j 3.-4.12310563j]
eigenvectors: [[ 0.83666003+0.j          0.83666003-0.j        ]
 [-0.23904572-0.49280538j -0.23904572+0.49280538j]]


## Generating random numbers

In [19]:
nums = np.random.randint(1,10,size = (3,3))
nums

array([[1, 3, 3],
       [5, 2, 8],
       [8, 8, 4]])

In [33]:
nums = np.random.normal(loc = 0,scale = 5,size = (3,3))
nums

array([[-3.34540493,  0.76756015, -1.61366157],
       [ 1.16016838, -0.76705198,  7.92621296],
       [-3.09562467, -0.27003422,  1.77995728]])

In [35]:
np.random.rand(3,3)

array([[0.18969724, 0.22765945, 0.79889675],
       [0.87341675, 0.03964159, 0.86527264],
       [0.04191786, 0.33251972, 0.42136322]])

## Setting random seed 

In [44]:
np.random.seed(42)

nums = np.random.randint(1,100,size = 3)
nums

array([52, 93, 15])

## Practice

In [9]:
a = np.arange(30,34).reshape(2,2)
b = np.arange(24,28).reshape(2,2)
np.matmul(a,b)

array([[1526, 1587],
       [1626, 1691]])

In [11]:
np.random.seed(42)
nums = np.random.randint(1,100,size = 3)
nums

array([52, 93, 15])