In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [34]:
b = np.array([[1,2],[4,5],[7,8]])
b

array([[1, 2],
       [4, 5],
       [7, 8]])

In [36]:
b.ndim

2

In [38]:
b.itemsize

8

In [40]:
b.dtype

dtype('int64')

In [42]:
b = np.array([[1,2],[4,5],[7,8]] , dtype = np.float32)

In [44]:
b.dtype

dtype('float32')

In [46]:
b.size

6

In [48]:
b.shape

(3, 2)

In [54]:
b = np.array([[1,2],[4,5],[7,8]] , dtype = complex)
b

array([[1.+0.j, 2.+0.j],
       [4.+0.j, 5.+0.j],
       [7.+0.j, 8.+0.j]])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [86]:
b = np.array([[1,2],[4,5],[7,8]])
b

array([[1, 2],
       [4, 5],
       [7, 8]])

In [88]:
b.reshape(2,3)

array([[1, 2, 4],
       [5, 7, 8]])

In [90]:
b.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [7],
       [8]])

In [98]:
b.ravel()

array([1, 2, 4, 5, 7, 8])

In [100]:
b

array([[1, 2],
       [4, 5],
       [7, 8]])

In [102]:
b.min()

1

In [104]:
b.max()

8

In [106]:
b.sum()

27

In [108]:
b.sum(axis = 0)

array([12, 15])

In [110]:
np.sqrt(b)

array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.64575131, 2.82842712]])

In [112]:
np.std(b)

2.5

In [114]:
a.dot(b)

array([[ 30,  36],
       [ 66,  81],
       [102, 126]])