In [4]:
import numpy as np

In [74]:
a = np.array([1,2,-3,4,5])
b = np.array([6,7,8,9,10])
a

array([1, 2, 3, 4, 5])

### Basic math functions

In [13]:
np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [19]:
np.subtract(b,a)

array([5, 5, 5, 5, 5])

In [21]:
np.multiply(a,b)

array([ 6, 14, 24, 36, 50])

In [23]:
np.divide(a,b)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

### Universal functions (ufuncst)

In [27]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [33]:
np.log(b)

array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [39]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [53]:
np.abs(a)

array([1, 2, 3, 4, 5])

### Aggregation functions

In [78]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a

array([1, 2, 3, 4, 5])

In [80]:
np.sum(a)

15

In [82]:
np.mean(a)

3.0

In [84]:
np.median(b)

8.0

In [86]:
np.std(a)

1.4142135623730951

In [88]:
np.var(b)

2.0

### Min/max values

In [103]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])


In [93]:
np.min(b)

6

In [95]:
np.max(a)

5

In [97]:
np.argmin(a)

0

In [99]:
np.argmax(b)

4