In [11]:
import numpy as np

In [3]:
n = [1,2,3,4,5]

In [5]:
n[0:2]

[1, 2]

In [7]:
n[-1]

5

In [13]:
a = np.array([1,2,3,4,5])

In [15]:
a[0:2]

array([1, 2])

In [17]:
a[-1]

5

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a[1,2]

6

In [33]:
a[0:2,2]

array([3, 6])

In [35]:
a[-1]

array([7, 8, 9])

In [37]:
a[-1,0:2]

array([7, 8])

In [43]:
a[:,1:2]

array([[2],
       [5],
       [8]])

In [45]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [47]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [57]:
a = np.arange(6).reshape(3,2)
print(a)
b = np.arange(6,12).reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [59]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [61]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [63]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [65]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [70]:
result = np.hsplit(a,3)

In [72]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [74]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [76]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [78]:
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [80]:
result = np.vsplit(a,2)

In [82]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [84]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [88]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [94]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [98]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])