### saving single numpy array

In [6]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
np.save('my_array.npy',arr)

In [6]:
loaded_arr = np.load('my_array.npy')
print(loaded_arr)

[1 2 3 4 5]


### save multiple array

In [20]:
arr1 = np.array([6,7,8,9,10])
arr2 = np.array([[11,12],[13,14]])
np.savez("multi_array.npz",first = arr1,second = arr2)

In [30]:
lead_multi_arr = np.load("multi_array.npz")
print(lead_multi_arr['first'])
print(lead_multi_arr['second'])

[ 6  7  8  9 10]
[[11 12]
 [13 14]]


### loading from txt

In [11]:
data = np.genfromtxt("student_depression_dataset.csv", delimiter=',', skip_header=1)
data

array([[2.00000e+00,         nan, 3.30000e+01, ..., 1.00000e+00,
                nan, 1.00000e+00],
       [8.00000e+00,         nan, 2.40000e+01, ..., 2.00000e+00,
                nan, 0.00000e+00],
       [2.60000e+01,         nan, 3.10000e+01, ..., 1.00000e+00,
                nan, 0.00000e+00],
       ...,
       [1.40689e+05,         nan, 3.10000e+01, ..., 2.00000e+00,
                nan, 0.00000e+00],
       [1.40690e+05,         nan, 1.80000e+01, ..., 5.00000e+00,
                nan, 1.00000e+00],
       [1.40699e+05,         nan, 2.70000e+01, ..., 3.00000e+00,
                nan, 1.00000e+00]])

### vectorization vs loops(why numpy is faster)

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6])
result = [a[i] + b[i] for  i in range (len(a))]
result

[5, 7, 9]